

1.   Initializing tensors
    
    1.1.  Initializing 1D tensor
    
    1.2  Initializing 2D tensor

    1.3   Initializing 3D tensor

    1.4  Randomly initializing tensors


2.   Mathematical operations in PyTorch

3.   Matrix operations in PyTorch

    3.1 Matrix addition

    3.2 Matrix subtraction

    3.3 Matrix multiplication

    3.4 Matrix division

    3.5 Transpose of a matrix

    3.6 Reshaping 2D tensors

4. Converting NumPy arrays to PyTorch tensors

5. Converting PyTorch Tensors to NumPy array




## 1. Initializing tensors

In [1]:
# import PyTorch library and checking its version
import torch
print(torch.__version__)

2.1.0+cu121


### 1.1.  Initializing 1D tensor

In [2]:
# initializing 1D tensor
one_d_tensor = torch.tensor([1])
print(one_d_tensor)

tensor([1])


In [3]:
# type of initialized tensor
type(one_d_tensor)

torch.Tensor

In [4]:
# data type of tensor
one_d_tensor.dtype

torch.int64

In [5]:
# shape of 1D tensor
one_d_tensor.shape

torch.Size([1])

### 1.2.  Initializing 2D tensor

In [6]:
# Initializing 2D tensor
two_d_tensor = torch.tensor([[1, 2], [3, 4]])
print(two_d_tensor)

tensor([[1, 2],
        [3, 4]])


In [7]:
# shape of 2D tensor
two_d_tensor.shape

torch.Size([2, 2])

### 1.3. Initializing 3D tensor

In [8]:
# Initializing 3D tensor
three_d_tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                                [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(three_d_tensor)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])


In [9]:
# shape of 3D tensor
three_d_tensor.shape

torch.Size([2, 3, 3])

### 1.4  Randomly initializing tensors

In [10]:
# setting random seed for PyTorch
torch.manual_seed(48)

# 1D tensor of random numbers
random_1d_tensor = torch.randn(6)
random_1d_tensor

tensor([ 1.0172, -2.1592, -0.6744,  0.5186,  1.0322,  0.6206])

In [11]:
# setting random seed for PyTorch
torch.manual_seed(48)

# 2D tensor of random numbers
random_2d_tensor = torch.randn(6, 3)
random_2d_tensor

tensor([[ 0.0770, -0.4779, -0.8114],
        [ 1.6048,  0.3736, -0.2863],
        [-0.0414, -1.6634,  0.6938],
        [ 0.5222,  0.6980, -0.2851],
        [-1.6273, -0.2667, -0.8868],
        [ 0.1195,  2.0794,  0.6585]])

In [12]:
# setting random seed for PyTorch
torch.manual_seed(48)

# 3D tensor of random numbers
random_3d_tensor = torch.randn(2, 3, 3)
random_3d_tensor

tensor([[[ 0.0770, -0.4779, -0.8114],
         [ 1.6048,  0.3736, -0.2863],
         [-0.0414, -1.6634,  0.6938]],

        [[ 0.5222,  0.6980, -0.2851],
         [-1.6273, -0.2667, -0.8868],
         [ 0.1195,  2.0794,  0.6585]]])

## 2.   Mathematical operations in PyTorch

In [13]:
# initializing two tensors
a = torch.tensor(4)
b = torch.tensor(2)

print(a, b)

tensor(4) tensor(2)


In [14]:
# addition
print(a + b)

# subtraction
print(a - b)

# division
print(a / b)

# multiplication
print(a * b)

tensor(6)
tensor(2)
tensor(2.)
tensor(8)


## 3.   Matrix operations in PyTorch

In [15]:
# setting random seed for pytorch and initializing two 2D tensors
torch.manual_seed(48)

a = torch.randn(3, 3)
b = torch.randn(3, 3)

In [16]:
print(a)

tensor([[ 1.0172, -2.1592, -0.6744],
        [ 0.5186,  1.0322,  0.6206],
        [ 1.0642, -0.5266,  0.1800]])


In [17]:
print(b)

tensor([[-1.1434,  1.3576,  0.1286],
        [-0.0734,  0.4420, -0.5520],
        [ 2.3109, -1.2542, -0.7957]])


### 3.1 Matrix addition

In [18]:
# adding two matrices using torch.add
addition = torch.add(a, b)
addition

tensor([[-0.1263, -0.8015, -0.5458],
        [ 0.4452,  1.4741,  0.0686],
        [ 3.3751, -1.7808, -0.6157]])

### 3.2 Matrix subtraction

In [19]:
# subtracting one matrix from other using torch.sub
subtraction = torch.sub(a, b)
subtraction

tensor([[ 2.1606, -3.5168, -0.8030],
        [ 0.5920,  0.5902,  1.1726],
        [-1.2467,  0.7276,  0.9758]])

### 3.3 Matrix multiplication

In [20]:
# matrix multiplication using torch.mm
# this is similar to dot product

dot_product = torch.mm(a, b)
dot_product

tensor([[-2.5630,  1.2725,  1.8593],
        [ 0.7654,  0.3819, -0.9969],
        [-0.7622,  0.9863,  0.2843]])

In [21]:
# matrix multiplication using torch.matmul

matrix_multiplication = torch.matmul(a, b)
matrix_multiplication

tensor([[-2.5630,  1.2725,  1.8593],
        [ 0.7654,  0.3819, -0.9969],
        [-0.7622,  0.9863,  0.2843]])

In [22]:
# matrix multiplication using torch.mul

elementwise_multiplication = torch.mul(a, b)
elementwise_multiplication

tensor([[-1.1630, -2.9313, -0.0867],
        [-0.0381,  0.4562, -0.3426],
        [ 2.4593,  0.6605, -0.1433]])

### 3.4 Matrix division

In [23]:
# divide one matrix by other using torch.div

division = torch.div(a, b)
division

tensor([[-0.8896, -1.5904, -5.2451],
        [-7.0652,  2.3354, -1.1242],
        [ 0.4605,  0.4199, -0.2263]])

###   3.5 Transpose of a matrix

In [24]:
# calculating transpose f 2D tensor in PyTorch

# original matrix
print(a, '\n')

# matrix transpose
torch.t(a)

tensor([[ 1.0172, -2.1592, -0.6744],
        [ 0.5186,  1.0322,  0.6206],
        [ 1.0642, -0.5266,  0.1800]]) 



tensor([[ 1.0172,  0.5186,  1.0642],
        [-2.1592,  1.0322, -0.5266],
        [-0.6744,  0.6206,  0.1800]])

###     3.6 Reshaping 2D tensors

In [25]:
# setting random seed for pytorch
torch.manual_seed(48)

# initializing tensor
a = torch.randn(4, 2)
a

tensor([[ 1.0172, -2.1592],
        [-0.6744,  0.5186],
        [ 1.0322,  0.6206],
        [ 1.0642, -0.5266]])

In [26]:
a.shape

torch.Size([4, 2])

In [27]:
# reshaping tensor using reshape function
b = a.reshape(1, 8)
b

tensor([[ 1.0172, -2.1592, -0.6744,  0.5186,  1.0322,  0.6206,  1.0642, -0.5266]])

In [28]:
b.shape

torch.Size([1, 8])

In [29]:
# reshaping tensor using view function
b = a.view(1, 8)
b

tensor([[ 1.0172, -2.1592, -0.6744,  0.5186,  1.0322,  0.6206,  1.0642, -0.5266]])

In [30]:
# sum of values in tensor
a.sum()

tensor(0.8925)

In [31]:
# average of values in tensor
torch.mean(a)

tensor(0.1116)

## 4. Converting NumPy arrays to PyTorch tensors

In [32]:
# imporing numpy library
import numpy as np

# initializing numpy array
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [33]:
type(a)

numpy.ndarray

In [34]:
# converting numpy array to tensor
array_to_tensor = torch.from_numpy(a)
array_to_tensor

tensor([[1, 2],
        [3, 4]])

In [35]:
type(array_to_tensor)

torch.Tensor


## 5. Converting PyTorch Tensors to NumPy array

In [36]:
# initializing ytorch tensor
a = torch.tensor([[1, 2], [3, 4]])
a

tensor([[1, 2],
        [3, 4]])

In [37]:
type(a)

torch.Tensor

In [38]:
# converting pytorch tensor to numpy array
tensor_to_array = a.numpy()
tensor_to_array

array([[1, 2],
       [3, 4]])

In [39]:
type(tensor_to_array)

numpy.ndarray